language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"

before_script:
  - npm install
script: './node_modules/.bin/nyc ./node_modules/.bin/ava'
after_success:
	- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'